In [2]:
import pandas as pd
data = pd.read_csv('breast_cancer.csv')
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
# removing id column
data.drop("id", axis = 'columns', inplace = True)

# removing Unnamed: 32 column
data.drop("Unnamed: 32", axis = 'columns', inplace = True)

In [4]:
# converting categorical target variable to numerical i.e. diagnosis
data.replace({"diagnosis" : {"M":1,"B":0}}, inplace = True)
data.diagnosis

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [5]:
# checking for relevant independent variables 
data.groupby("diagnosis").mean()

# based on the mean we remove:
# 1.) symmetry_mean
# 2.) fractal_dimension_mean
# 3.) smoothness_worst
# 4.) fractal_dimension_worst
# from our analysis

radius_mean  texture_mean  perimeter_mean   area_mean  \
diagnosis                                                          
0            12.146524     17.914762       78.075406  462.790196   
1            17.462830     21.604906      115.365377  978.376415   

           smoothness_mean  compactness_mean  concavity_mean  \
diagnosis                                                      
0                 0.092478          0.080085        0.046058   
1                 0.102898          0.145188        0.160775   

           concave points_mean  symmetry_mean  fractal_dimension_mean  ...  \
diagnosis                                                              ...   
0                     0.025717       0.174186                0.062867  ...   
1                     0.087990       0.192909                0.062680  ...   

           radius_worst  texture_worst  perimeter_worst   area_worst  \
diagnosis                                                              
0             13.379801      23.515070        87.005938   558.899440   
1             21.134811      29.318208       141.370330  1422.286321   

           smoothness_worst  compactness_worst  concavity_worst  \
diagnosis                                                         
0                  0.124959           0.182673         0.166238   
1                  0.144845           0.374824         0.450606   

           concave points_worst  symmetry_worst  fractal_dimension_worst  
diagnosis                                                                 
0                      0.074444        0.270246                 0.079442  
1                      0.182237        0.323468                 0.091530  

[2 rows x 30 columns]

In [6]:
# dropping these variables from our data
data.drop(['symmetry_mean', 'fractal_dimension_mean', 'smoothness_worst', 'fractal_dimension_worst'], axis = 'columns', 
         inplace = True)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [9]:
x = data.drop('diagnosis', axis = 'columns')

In [10]:
y = data.diagnosis

In [33]:
from sklearn.model_selection import cross_val_score
lr_score = cross_val_score(LogisticRegression(max_iter = 3500), x,y, cv = 5)
lr_score

array([0.93859649, 0.94736842, 0.98245614, 0.92982456, 0.96460177])

In [34]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators = 100), x,y, cv = 5)
rf_score

array([0.92105263, 0.93859649, 0.98245614, 0.97368421, 0.99115044])

In [35]:
dt_score = cross_val_score(DecisionTreeClassifier(), x,y, cv = 5)
dt_score

array([0.90350877, 0.9122807 , 0.92105263, 0.95614035, 0.92035398])

In [36]:
svm_score = cross_val_score(SVC(), x,y, cv = 5)
svm_score

array([0.85087719, 0.89473684, 0.92982456, 0.93859649, 0.9380531 ])

In [38]:
# taking mean of all scores and selecting the best algorithm
import numpy as np
print("Mean logistic regression score is: ",np.mean(lr_score))
print("Mean random forest score: ",np.mean(rf_score))
print("Mean decision tree score: ",np.mean(dt_score))
print("Mean support vector machine score: ",np.mean(svm_score))

Mean logistic regression score is:  0.9525694767893184
Mean random forest score:  0.9613879832324173
Mean decision tree score:  0.9226672876882471
Mean support vector machine score:  0.9104176370128861


# So the best algorithm for our dataset is Random Forest